<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en-gb" lang="en-gb">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
<meta name="keywords" content="International Regulators' Forum Global Offshore Safety" />
<meta name="description" content="International Regulators' Forum Global Offshore Safety" />
<meta name="author" content="International Regulators' Forum Global Offshore Safety" />
<meta name="robots" content="index, follow" />

<title>International Regulators' Forum Global Offshore Safety</title>

<link href="/shared/styles.css" rel="stylesheet" type="text/css" />
</head>

<body>
<!--#include virtual="/shared/header.aspx" -->
<table width="750" border="0" align="center" cellpadding="0" cellspacing="0" summary="Offshore Safety Forum">
  <tr>
    <td width="159" valign="top"><!--#include virtual="/shared/conferencestree.aspx" --><!--#include virtual="/shared/search.aspx" --></td>
    <td width="1" bgcolor="#c9c9c9"><img src="/images/_.gif" alt="" width="1" height="1" /></td>
    <td valign="top">
	<table border="0" cellpadding="20" cellspacing="0" summary="Offshore Safety Forum">
      <tr>
        <td valign="top"><!--#include virtual="/shared/newsdropdown.aspx" -->
          <br />

          <h2> 2007 conference Speakers</h2>
          <p>&nbsp;</p>
          <h3>Dirk Kempthorne, USA<br />
            Secretary of the U.S. Department of the Interior</h3>
          <p><img src="/conferences/2007conference/speakers/DirkKempthorne.jpg" alt="Dirk Kempthorne, USA" width="134" height="156" hspace="10" align="left" /></p>
          <p>Dirk Kempthorne was confirmed as the 49th Secretary of the U.S. Department of the Interior on May 26, 2006, in a voice vote by the U.S. Senate. Mr. Kempthorne took the oath of office on the same day.</p>
          <p>Prior to his confirmation as Secretary, Mr. Kempthorne served nearly two terms as Governor of Idaho, elected first in 1998 and re-elected in 2002.</p>
          <p>As Governor, Mr. Kempthorne worked to develop consensus on management of Idaho's and the West's natural resources. He worked with his colleagues in Oregon, Washington and Montana to develop an historic bipartisan agreement on a state-based solution for returning salmon runs in the region. Following the devastating wildfires of 2000, he worked with fellow western governors and federal officials to fundamentally change the approach to forest health and wildfire management. Under his leadership, Idaho developed wolf and grizzly bear management plans aimed at delisting the endangered species and giving the State of Idaho management responsibilities.</p>
          <p>Before his terms as Governor, Mr. Kempthorne completed a successful 6-year term in the United States Senate (1993-1999). As a Senator, he wrote, negotiated, and won passage of two major pieces of legislation: a bill to end unfunded federal mandates on state and local governments, and a substantial revision of the federal Safe Drinking Water Act. He also worked to improve the quality of life for American active-duty military personnel, reservists, their families and veterans.</p>
          <p>Dirk Kempthorne began his commitment to public service as the highly successful Mayor of the City of Boise (1985-1992). During his seven years in office, he helped direct a renaissance in the state's capital city that resulted in record growth, economic development and numerous national honors and recognitions for quality of life, business climate and family issues.</p>
          <p>Secretary Kempthorne has been recognized by his peers as a national leader. As Governor, his colleagues elected him as the Chairman of the National Governors Association in August of 2003. He has served as President of the Council of State Governments and Chairman of the Western Governors Association. He served on the Executive Committees of the National Governors Association and the Republican Governors Association. Secretary of Education Rod Paige appointed then-Governor Kempthorne to the National Assessment Governing Board and Secretary of Homeland Security Tom Ridge appointed him to the Homeland Security Task Force.</p>
          <p>Secretary Kempthorne and his wife Patricia are both University of Idaho graduates and have two grown children, Heather and Jeff.</p>
          <p>&nbsp;</p>
          <h3>Ellen Seip, Norway <br />
            Secretary General of the Norwegian Ministry of Labour and Social Inclusion</h3>
          <p><img src="/conferences/2007conference/speakers/EllenSeip.jpg" alt="Ellen Seip, Norway" width="134" height="156" hspace="10" align="left" />Ellen Seip has a Master's Degree of Sociology and is a Norwegian civil servant. She was engaged by the Ministry of Social Affairs in 1980, became Director General in 1987, and appointed Deputy Secretary General in 1999. In 2002, she was appointed Secretary General of the Ministry of Social Affairs. From 2002-03 she was Secretary General of the Ministry of Labour and Administration and from 2004 of the newly established Ministry of Labour and Social Affairs, which in 2006 was renamed the Ministry of Labour and Social Inclusion. The Ministry is responsible for Labour market policy, Working Environment and Safety, Poverty and Welfare, Integration and Diversity, Sami and Minority Affairs and Migration.</p>
          <p>Ms. Seip holds a central position in the implementation of Norway's new labor and welfare administration, which also spends the greater part of Norway's state budget.</p>
          <p>&nbsp;</p>
          <h3>Randall B. Luthi, USA <br />
            Director, Minerals Management Service</h3>
          <p><img src="/conferences/2007conference/speakers/RandallBLuthi.jpg" alt="Randall B. Luthi, USA" width="134" height="156" hspace="10" align="left" />Randall B. Luthi was appointed Director of the Minerals Management Service on July 23, 2007. Mr. Luthi, a former speaker of the Wyoming State House of Representatives, is a rancher and attorney in private practice from Freedom, Wyoming. He previously served in the Department of the Interior and at the National Oceanic and Atmospheric Administration (NOAA).</p>
          <p>Mr. Luthi is a partner in the Luthi and Voyles law firm in Thayne, Wyoming, and manages a cattle ranch in western Wyoming. He was first elected to the Wyoming House of Representatives in 1995, and served as speaker in 2005 and 2006. </p>
          <p>He served in Washington in career positions as Senior Counselor for Environmental Regulations in NOAA's Office of General Counsel from 1990 to 1993, and as an attorney in the Department of the Interior Office of the Solicitor from 1986 to 1990.</p>
          <p>Based on his work in the Wyoming legislature, Mr. Luthi developed an understanding of the importance of royalties paid to the federal government by companies producing energy on our public lands and waters. As Majority Leader and Speaker of the Wyoming House, Mr. Luthi was instrumental in formulation of state budgets which relied heavily upon royalties and severance taxes paid by energy companies developing federal leases. In addition, he was a legislative member of the Energy Council, which is an organization comprised of legislative representatives from energy producing states and provinces and private energy-related industries that meets quarterly to learn the latest in developments in energy related technology and to discuss energy policy.</p>
          <p>In addition, Mr. Luthi worked as a legislative assistant in the office of U.S. Senator Alan K. Simpson of Wyoming. In this capacity, Mr. Luthi provided counsel on legal and legislative issues including oil and gas taxation.</p>
          <p>Mr. Luthi graduated from the University of Wyoming in 1979 with a Bachelor of Science Degree in administration of justice, and earned a law degree from the University of Wyoming in 1982.</p>
          <p>&nbsp;</p>
          <h3>Matthew R. Simmons, USA <br />
            Chairman, Simmons &amp; Company International</h3>
          <p><img src="/conferences/2007conference/speakers/MatthewRSimmons.jpg" alt="Matthew R. Simmons, USA" width="134" height="156" hspace="10" align="left" />Matthew R. Simmons is Chairman of Simmons &amp; Company International, a specialized energy investment banking firm. The firm has completed approximately 629 investment banking projects for its worldwide energy clients at a combined dollar value in excess of $84 billion.</p>
          <p>Mr. Simmons was raised in Kaysville, Utah. He graduated cum laude from the University of Utah and received an MBA with Distinction from Harvard Business School. He served on the faculty of Harvard Business School as a Research Associate for 2 years and was a Doctoral Candidate.</p>
          <p>Mr. Simmons began a small investment bank/advisory firm in Boston. Among his early clients were several subsea service companies. By 1973, almost all of his clients were oil service companies. Following the 1973 oil shock, Simmons decided to create a Houston-based firm to concentrate on providing highest quality investment banking advice to the worldwide oil service industry. Over time, the specialization expanded into investment banking covering all aspects of the global energy industry.</p>
          <p>Today the firm has approximately 145 employees and enjoys a leading role as one of the largest energy investment banking groups in the world. Its offices are in Houston, Texas; London, England; Boston, Massachusetts; and Aberdeen, Scotland.</p>
          <p>He serves on the Board of Directors of Brown-Forman Corporation, The Initiative for a Competitive Inner City (Boston), Houston Technology Center (Houston), and the Center for Houston&rsquo;s Future (Houston). He also serves on The University of Texas&rsquo; M.D. Anderson Cancer Center Foundation Board of Visitors (Houston) and is a Trustee of the Bermuda Biological Station for Research. In addition, he is past Chairman of the National Ocean Industry Association. Mr. Simmons serves on the Board of Dean&rsquo;s Advisors of Harvard Business School and is a past President of the Harvard Business School Alumni Association and a former member of the Visiting Committee of Harvard Business School. He is a member of the National Petroleum Council, Council on Foreign Relations and The Atlantic Council of the United States. Mr. Simmons is a Trustee of The Farnsworth Art Museum in Rockland, Maine, and is also a Trustee of the National Trust for Historic Preservation.</p>
          <p>Mr. Simmons&rsquo; recently published book Twilight in the Desert: The Coming Saudi Oil Shock and the World Economy has been listed on the Wall Street Journal&rsquo;s best-seller list. He has also published numerous energy papers for industry journals and is a frequent speaker at government forums, energy symposiums, and in board rooms of many leading energy companies around the world.</p>
          <p>Mr. Simmons is married and has 5 daughters. His hobbies include watercolours, cooking, writing, and travel.</p>
          <p>&nbsp;</p>
          <h3>Gary P. Luquette, USA <br />
            Vice President, Chevron Corporation, and <br />
            President, Chevron North America Exploration and Production Co.</h3>
          <p><img src="/conferences/2007conference/speakers/GaryPLuquette.jpg" alt="Gary P. Luquette, USA" width="100" height="133" hspace="10" align="left" />Gary Luquette is a vice president of Chevron Corporation and is president of Chevron North America Exploration and Production Co. headquartered in Houston, Texas. The company is charged with managing exploration, production, and development activities of Chevron's North America asset base. He assumed his current position April 1, 2006.</p>
          <p>Prior to his current position, Mr. Luquette was the president and managing director of Chevron Upstream Europe, headquartered in Aberdeen, Scotland; he assumed that position in February 2003. From June 1996 until assuming his position in Scotland, he served as profit center manager and then vice president of Chevron's San Joaquin Valley heavy oil operations in California. From 1993 until 1996, he served as manager of enhanced-recovery projects for PT. Caltex Pacific Indonesia in Sumatra, Indonesia. He has held various assignments in Chevron U.S.A. Production Co., Chevron Pipe Line Co. and Chevron Corporation throughout his more than 25-year career.</p>
          <p>In 1978, Mr. Luquette graduated with a Bachelor of Science degree in civil engineering from the University of Louisiana at Lafayette. He hails from Abbeville, Louisiana.</p>
          <p>Mr. Luquette is a member of the American Petroleum Institute's Upstream Committee and a member of the executive board of the Greater Houston Partnership. Earlier he served as chairman of the Step Change in Safety Leadership Team (a U.K. oil and gas industry health and safety initiative). He also served as a member of the United Kingdom Offshore Operators Association council and board, the Industry Leadership Team and PILOT (a U.K. government and industry collaborative forum for addressing major industry issues).</p>
          <p>&nbsp;</p>
          <h3>Jean P. Cahuzac, USA <br />
            President, Transocean Inc.</h3>
          <p><img src="/conferences/2007conference/speakers/JeanCahuzac.jpg" alt="Jean P. Cahuzac, USA" width="134" height="156" hspace="10" align="left" />Mr. Cahuzac is currently President of Transocean, Inc. Previously, he served the company as Executive Vice President and Chief Operating Officer.</p>
          <p>Mr. Cahuzac has over 27 years of experience within the oil and gas industry, having held various technical and senior management positions around the world. His service included technical and managerial positions in countries such as Nigeria, Congo, Brazil, and the United Kingdom. While working for Schlumberger -- Sedco Forex -- he was appointed as Vice President of Engineering in 1989, Vice President, Europe &amp; Africa Business Unit, in 1994, and Sedco Forex President in early 1999.</p>
          <p>Mr. Cahuzac earned a degree in France from Ecole des Mines Saint Etienne and the French Petroleum Institute. He is both an active member and director of the International Association of Drilling Contractors and a member in the Society of Petroleum Engineers.</p>
          <p>&nbsp;</p>
          <h3>Elmer P. Danenberger, III, USA <br />
            Chief, Office of Offshore Regulatory Programs, Minerals Management Service</h3>
          <p><img src="/conferences/2007conference/speakers/ElmerPDanenberger.jpg" alt="Elmer P. Danenberger, III, USA" width="134" height="156" hspace="10" align="left" />Mr. Danenberger earned a B.S. degree in Petroleum and Natural Gas Engineering and a Masters degree in Environmental Pollution Control, both from Pennsylvania State University. He has been employed as an engineer in the Department of the Interior&rsquo;s offshore oil and gas program since 1971. He served as a staff engineer in the Gulf of Mexico regional office; Chief of the Technical Advisory Section at the headquarters office of the U.S. Geological Survey; District Supervisor for MMS field offices in Santa Maria, California, and Hyannis, Massachusetts; and as Chief of the Engineering and Operations Division at MMS headquarters.</p>
          <p>He is currently Chief, Office of Offshore Regulatory Programs, with responsibilities for safety and pollution-prevention research, engineering support, operating regulations, and inspection and enforcement programs.</p>
          <p>&nbsp;</p>
          <h3>Magne Ognedal, Norway <br />
            Director, Petroleum Safety Authority Norway</h3>
          <p><img src="/conferences/2007conference/speakers/MagneOgnedal.jpg" alt="Magne Ognedal, Norway" width="134" height="156" hspace="10" align="left" />Mr. Ognedal is a graduate from the University of Newcastle upon Tyne (1967) with a BSC in Mechanical Engineering and Electrical Engineering.</p>
          <p>He has experience from automation of ship engine rooms and in automatisation of industrial processes.</p>
          <p>Employed by the Norwegian Petroleum Directorate from 1974, starting as a Petroleum Engineer, later became Section Manager and from 1980 Director Safety and Working Environment Division, dealing with all aspects within safety and working environment for Norwegian offshore installations.</p>
          <p>At present, Mr. Ognedal is Director for the Petroleum Safety Authority Norway.</p>
          <p>&nbsp;</p>
          <h3>J. W. (Jan) de Jong, Netherlands <br />
            Inspector-General of Mines for the State Supervision of Mines</h3>
          <p><img src="/conferences/2007conference/speakers/JW_de-Jong.jpg" alt="J. W. (Jan) de Jong, Netherlands" width="134" height="156" hspace="10" align="left" />Mr. de Jong is presently the Inspector&ndash;General of Mines for the State Supervision of Mines, Netherlands. The State Supervision of Mines is a supervising agency of the Ministry of Economic Affairs.  It ensures that the extraction of natural resources in the Netherlands is carried out in a socially responsible way. Supervision of oil, gas, salt and marl mining in the Netherlands covers safety, health, environmental matters, subsidence, earth tremors and the effective production of minerals.</p>
          <p>Mr. de Jong received a Bachelors degree in mechanical engineering and specialized in energy-technology from Technical College. He also studied at Heriot Watt University where he earned a Masters degree in petroleum engineering. His thesis subject was the cleaning of cuttings from North Sea drilling rigs.</p>
          <p>Mr. de Jong worked from 1975-1989 for Shell Internationale Petroleum Maatschappij (SIPM) where he worked in the drilling operations department in various functions  such as trainee-driller, assistant driller, driller, well site petroleum engineer, operations engineer and toolpusher within several SIPM operating companies in the Netherlands, Oman, Brunei and the UK.  During the last year working in the drilling engineering / research departments as a  member of the SIPM/KSEPL drilling cost reduction spearhead team, initiating and assisting in the implementation of cost-reducing measures (technical and economical) within various operating companies of Shell.  Disseminating the experience with these measures throughout the group of operating companies of the Shell group.  At the same time coordinating a number of drilling-research projects.  Co-author of several exploration and production and research reports.</p>
          <p>Since 1987, he has worked for the State Supervision of Mines (SSM). Commenced as Head of Operations, responsible for the operational activities, i.e., inspecting, auditing, investigating, enforcing and assessing of plans, programs, reports and safety cases.  Since 1992 special responsibility for the management of change (from hardware inspections towards auditing , verification and monitoring of management systems) and stimulating the companies to adopt and implement integrated management systems for safety, health and environment based on quality management systems like ISO 9000 and ISO 14000.</p>
          <p>Mr. de Jong was appointed in 1989 as Deputy Inspector General responsible for advising the ministry, drafting of regulations, contacts with employers (and their associations), employees (and unions), other governmental agencies and the media.  Since 1997, he has been responsible for directing the supervision towards a process based approach with special attention for critical sub processes and activities.  Convincing, stimulating and supervising that the industry does the same and adapt their management accordingly was part thereof.  Company Environmental Plans, Environmental Impact Studies and Safety and Health documents are the most important instruments for the management of risk for both the companies and for the Dutch government supervising the mining activities. </p>
          <p>Mr. de Jong was finally appointed as Inspector&ndash;General of Mines in 2003 responsible for managing the SSM organization as a whole.</p>
          <p>&nbsp;</p>
          <h3>Taf Powell, United Kingdom <br />
            Program Committee Chairman <br />
            Investigation Manager, Buncefield Board</h3>
          <p><img src="/conferences/2007conference/speakers/TafPowell.jpg" alt="Taf Powell, United Kingdom" width="134" height="156" hspace="10" align="left" />Taf Powell is head of Health and Safety Executive&rsquo;s (HSE) Offshore Division. He graduated in Geology and Chemistry from Nottingham University. His oil field career has been split between working in the UK and abroad in offshore exploration and development and regulation of the sector in licensing, well operations, policy and safety regulation. </p>
          <p>In 1991, he joined the HSE&rsquo;s Offshore Division from BP and started work to develop the new offshore regulatory framework, one of Lord Cullen&rsquo;s recommendations following his inquiry into the Piper Alpha disaster.</p>
          <p>As HSE&rsquo;s Operations Manager, based in Aberdeen, he led inspection teams and well engineer specialists responsible for enforcing the new regulations until 2000 when he took up the role as Director and Chief Inspector of the Offshore Division of the HSE&rsquo;s Hazardous Industries Directorate.</p>
          <p>Taf has been working with the International Regulators Forum promoting the economic sustainability agenda worldwide&ndash;and gaining additional leverage with the worldwide drilling and production industry since its creation in 1994.</p>
          <p>In December 2005, Taf was appointed to lead the Government&rsquo;s investigation into the Buncefield Major Incident of December 11, 2005. The investigation reports to an independent Board, of which Taf is a member.</p>
          <p>Taf is married to Judy, with a son and daughter. They live in Aberdeen, Scotland. When spared from work and household maintenance, his interests include outdoor activities, particularly hill walking.</p>
          <p>&nbsp;</p>
          <h3>John Mogford, United Kingdom <br />
            BP Senior Group Vice President, Safety &amp; Operations </h3>
          <p><img src="/conferences/2007conference/speakers/JohnMogford.jpg" alt="John Mogford, United Kingdom" width="134" height="156" hspace="10" align="left" />John Mogford has worked for over 33 years in the oil and gas industry, mainly in Upstream Exploration and Production. In light of the Texas City incident John was appointed Senior Group Vice President of Safety &amp; Operations, reporting to Tony Hayward. Previous to this role, John returned to E&amp;P to take up the position of Group Vice President, Technology and Decentralised Functions. His roles prior to joining E&amp;P included Group Vice President for Gas, Power &amp; Renewables, and his remit covering the areas of Wind, Hydrogen, Solar and NGL&rsquo;s. John is also a great champion for Health and Safety and from 1999 to 2002 he was Group Vice President for Health, Safety and Environment. Prior to this, he was Technology Vice President with specific responsibilities for drilling, production operations and HSE for BP&rsquo;s global E&amp;P activities. In the early 90&rsquo;s, John was manager of BP&rsquo;s North Seas Forties Field after a spell as Technical Manager for North Sea operations having worked in field and drilling roles culminating in the position of global drilling manager for BP. </p>
          <p>He has worked in a variety of geographical regions including London, Alaska, the Gulf of Mexico, Egypt and the North Sea.</p>
          <p>After graduating from Sheffield University as a mechanical engineer, John joined the oil and gas industry working for Schlumberger Oilfield Services before joining BP in 1977. </p>
          <p>He is married and has two children.</p>
          <p>&nbsp;</p>
          <h3>Glenn Erwin, USA <br />
            Project Director of the Triangle of Prevention Program for International Union United Steelworkers International Union</h3>
          <p><img src="/conferences/2007conference/speakers/GlennErwin.jpg" alt="Glenn Erwin, USA" width="134" height="156" hspace="10" align="left" />Glenn Erwin is a member of the USW (United Steelworkers International Union) Health, Safety and Environment Department and is the Project Director of the Triangle of Prevention (TOP) Program for International Union.</p>
          <p>Mr. Erwin has worked within the Petrochemical Industry for over 40 years in various positions ranging from pipeline construction to Chemical Plant Operations and Maintenance. During this period he has co-authored over 50 publications relating to Health and Safety within the Petrochemical Industry, reviewed or analyzed hundreds of incident/accident investigations and made numerous presentations to leading industry workgroups.</p>
          <p>He has been actively involved in the Union movement throughout this career serving in several elected positions such as Steward, Trustee, Vice-President and President of the Oil, Chemical, and Atomic Workers Local 4-449 Texas City, Texas.</p>
          <p>Mr. Erwin has extensive experience in accident investigation within the Petrochemical Industry and he is very knowledgeable in the area of Health &amp; Safety. In 2005, he testified before the U.S. Senate Homeland Security and Government Affairs Committee in their examination the appropriate role of the Federal government in efforts to better protect the nation&rsquo;s chemical facilities from terrorist attacks. He also served as a member of the Independent Safety Review Panel requested by the United States Chemical and Hazards Board to review the North American Refinery operations of British Petroleum.</p>
          <p>&nbsp;</p>
          <h3>Charles Bowen, United Kingdom<br />
            Executive Director, International Association of Oil and Gas Producers</h3>
          <p><img src="/conferences/2007conference/speakers/CharlesBowen.jpg" alt="Charles Bowen, United Kingdom" width="134" height="156" hspace="10" align="left" />Charles Bowen took over as Executive Director of the International Association of Oil and Gas Producers in February 2005, after a 30-year career with TOTAL. He spent his early career in development projects, and then moved into production management, HSE management and then general management.</p>
          <p>He had several assignments in the Middle East, amounting to some 10 years in all, and spent 8 years working in the North Sea.</p>
          <p>&nbsp;</p>
          <p>&nbsp;</p>
          <h3>Dr. Lee Hunt, USA <br />
            President, International Association of Drilling Contractors</h3>
          <p><img src="/conferences/2007conference/speakers/LeeHunt.jpg" alt="Dr. Lee Hunt, USA" width="134" height="156" hspace="10" align="left" />Dr. Lee Hunt serves as the Chief Executive of IADC, responsible for managing IADC's worldwide operations. Before being named President in 1990, his prior Association positions included Manager for State Government Affairs, Environmental Affairs and Human Resources. Dr. Hunt holds a PhD in political science from Northwestern University and received his law degree from South Texas College of Law.</p>
          <p>&nbsp;</p>
          <p>&nbsp;</p>
          <h3>Tad LeBlanc, USA<br />
            Vice President, HSE&amp;C, Baker Energy </h3>
          <p><img src="/conferences/2007conference/speakers/TadLeBlanc.jpg" alt="Tad LeBlanc, USA" width="134" height="156" hspace="10" align="left" />Tad LeBlanc has worked in the oil and gas industry for over 25 years and has been with Baker Energy in Houston, TX for the past 14 years. Mr. LeBlanc has served in various positions ranging from operations and maintenance to health, safety, environment, and compliance.</p>
          <p>In his current position, Mr. LeBlanc is responsible for the overall management for Baker Energy&rsquo;s Health, Safety, Environment &amp; Compliance Program worldwide. His team ensures compliance with required federal, state, and international regulatory agencies and client contractual obligations. Significant accomplishments while managing the HSE&amp;C Team include:</p>
          <ul>
            <li>National MMS SAFE Award Finalist and Winner for Production Contractor Category in 2005.</li>
            <li> National MMS SAFE Award Finalist and Winner for Production Contractor Category in 2006. </li>
            <li>Eight MMS District Production Contractor SAFE Awards beginning in 2003. </li>
            <li>The distinction of being the only production contract company to win three (of the five) MMS District Awards. This was achieved two years in a row (2005 &amp; 2006). </li>
            <li>One of 22 individuals in the U.S. awarded the 2006 Corporate Leadership Award (CORLA) </li>
          </ul>
          <p>Mr. LeBlanc graduated from Nichols State University in Thibodeaux, Louisiana, with degrees in Petroleum Technology and Petroleum Safety.</p>
          <p>&nbsp;</p>
          <h3>Melinda Mayes, USA<br />
            Chief, Accident Investigation Board, MMS</h3>
          <p><img src="/conferences/2007conference/speakers/MelindaMayes.jpg" alt="Melinda Mayes, USA" width="134" height="156" hspace="10" align="left" />Melinda Mayes currently serves as the Chief, Accident Investigation Board, of the Minerals Management Service in Herndon, Virginia. The Board is responsible for overseeing MMS's programs for investigating offshore accidents and analyzing accident data. The Board works with both Regional and District offices to establish appropriate policies and procedures for accident investigation and data management.</p>
          <p>Ms. Mayes has worked for MMS for 18 years, including work in the Pacific Regional office in the areas of offshore facility plan review, coordination with State and local agencies, and offshore development and unitization. Before coming to MMS, she worked for 7 years as a Petroleum Geologist for ARCO Oil and Gas Company in Texas and Colorado.</p>
          <p>&nbsp;</p>
          <h3>Saif Al-Naimi, Qatar <br />
            HSE Director General</h3>
          <p><img src="/conferences/2007conference/speakers/SaifAl-Naimi.jpg" alt="Saif Al-Naimi, Qatar" width="134" height="156" hspace="10" align="left" />Mr. Saif S Al Naimi, Director of the HSE Regulations and Enforcement Directorate is vested with the primary responsibilities to  stipulate the Regulations and follow up to ensure that the players in the petroleum activities maintain high standards of health, environment, safety and emergency preparedness and thereby contribute in creating the greatest possible values for the society. As Director of the Regulations &amp; Enforcement Directorate has Regulatory &amp; Enforcement responsibility to ensure  for HSE  and the working environment in the petroleum activities.</p>
          <p>The appointment  to the role of Director HSE regulations &amp; Enforcement Directorate  has been a journey of challenges after being graduated in Chemical Engineering from Qatar University. After graduation, he joined QP and worked in the various capacities. He became Manager, Corporate Quality &amp; Management Systems and was responsible for managing all aspects of the Quality Management System and its development throughout the Corporation and managed all quality issues related to projects very meticulously.</p>
          <p>The present job responsibilities requires to liaison with national, regional and  International Institutions and Organisations in relation to treaties, protocols and agreements involving HSE issues and Sustainable Development in order to develop and maintain synergies between HSE local Regulations and the International developments.</p>
          <p>In the field of Standardisation, Mr, Saif Al Naimi played a major role  in establishing the QP Standardisation Management System and in involving QP in the national, and international standardisation efforts which lead to the establishment of the Gulf Standards Committee for oil and gas industry, which he is chairing now as Qatar Petroleum representative.</p>
          <p>An articulate visionary in Management Systems, and Regulatory issues, Mr. Saif with his impeccable leadership and management skills  has been instrumental in the implementation of Management Systems, Standards, Regulations and Continuous Improvement Programs.</p>
          <p>&nbsp;</p>
          <h3>Alan Richardson, United Kingdom<br />
            Specialist Inspector, Health &amp; Safety Executive <br />
            (Fire, Explosion, and Risk Assessment)</h3>
          <p><img src="/conferences/2007conference/speakers/AlanRichardson.jpg" alt="Alan Richardson, United Kingdom" width="134" height="156" hspace="10" align="left" />Alan Richardson has 25 years experience in upstream and downstream risk assessment, major hazard testing and offshore safety regulation. He spent 12 years at the British Gas Engineering Research Station including 7 years as a Project Engineer at their Spadeadam Major Hazard Test Site. This was followed by 6 years with Lloyd&rsquo;s Register in the U.K. and Far East carrying out onshore and offshore risk assessments, writing offshore safety cases, and running a design verification project. Mr. Richardson joined the U.K. HSE in 1998 as a Specialist Inspector (fire, explosion and risk assessment) and has managed Key Programme 3, Asset Integrity Inspection, since 2005.</p>
          <p>&nbsp;</p>
          <h3>Iain Paterson, United Kingdom <br />
            Principal Inspector of Health &amp; Safety <br />
            Health &amp; Safety Executive Offshore Division</h3>
          <p><img src="/conferences/2007conference/speakers/IainPaterson.jpg" alt="Iain Paterson, United Kingdom" width="134" height="156" hspace="10" align="left" />Iain Paterson is a Principal Inspector with the Health and Safety Executive and has been employed by them for the last 14 years. He is a Chartered Engineer and leads the Offshore Mechanical Engineering team, concentrating on the integrity of pressure systems, maintenance, and lifting issues. Iain chairs the Lifting Working Group of the International Regulators' Forum, a forum of offshore regulators from around the world, and he will tell us a little about that work during his presentation. He has also helped devise HSE's inspection programme KP2 concentrating on the management of offshore lifting operations. Before his involvement in offshore work, Iain led HSE's onshore lifting team, concentrating mostly on the construction industry. He has been involved in the development of European standards for wire rope, lifting chain, and below the hook lifting accessories. Before joining HSE, Iain worked in coal mining, aerospace, and nuclear industries.</p>
          <p>&nbsp;</p>
          <h3>John Clegg, Australia <br />
            CEO, Australian National Offshore Petroleum Safety Authority</h3>
          <p><img src="/conferences/2007conference/speakers/JohnClegg.jpg" alt="John Clegg, Australia" width="134" height="156" hspace="10" align="left" />John Clegg spent 29 years in the Health and Safety Executive (HSE) in the UK regulating mainly onshore and offshore major hazard industries. Following the Piper Alpha disaster in the North Sea, John, an Operations Manager, helped set up the Offshore Division and contributed to the regime change from prescription to goal setting.</p>
          <p>John took up post as the inaugural CEO of the Australian National Offshore Petroleum Safety Authority (NOPSA) on July 1, 2004.</p>
          <p>&nbsp;</p>
          <p>&nbsp;</p>
          <h3>Ahmed Mubarak, Qatar <br />
            Manager, HSE Monitoring and Performance Department, Qatar Petroleum</h3>
          <p><img src="/conferences/2007conference/speakers/AhmedMubarak.jpg" alt="Ahmed Mubarak, Qatar" width="134" height="156" hspace="10" align="left" />Ahmed Mubarak received his PhD in Chemical Technology in 1976. He has authored and co-authored over 50 books and technical articles which have been published in various engineering/technology and science journals. He served as Principal Auditor [IRCA registered] for Quality [ISO 9001], Environment [ISO 14001], and Occupational Health and Safety [OHSAS 18001].</p>
          <p>Mr. Mubarak has 25 years experience in the chemical and oil and gas industry and is currently Manager of HSE Monitoring &amp; Performance Dept, Qatar Petroleum.</p>
          <p>&nbsp;</p>
          <h3>J. B. Verma, India <br />
            Executive Director, Oil Industry Safety Directorate</h3>
          <p><img src="/conferences/2007conference/speakers/JBVerma.jpg" alt="J. B. Verma, India" width="134" height="156" hspace="10" align="left" />J. B. Verma is a Chemical Engineer from the Indian Institute of Technology, Delhi, India. He has 32 years experience in Indian Oil Corporation Limited (IOCL), a Fortune 500 company in the petroleum refining, manufacturing and marketing sector of the oil industry. </p>
          <p>Mr. Verma has rich experience in diversified fields of Technical Services, Operations and Commissioning of Hydrogen, Hydro-desulphurization, and Hydrocracker Plants of IOCL Mathura Refinery. He has worked in the Gujarat, Guwahati, Haldia and Mathura Refineries of IOCL in various departments.</p>
          <p>Presently, he is the Executive Director, heading Oil Industry Safety Directorate (OISD), a technical directorate under the Ministry of Petroleum and Natural Gas (MOP&amp;NG), Government of India, that formulates and coordinates the implementation of a series of self-regulatory standards in the areas of design, operation and maintenance, aimed at enhancing the safety in the Oil &amp; Gas Industry in India. He is steering and guiding the safety aspects in the Oil &amp; Gas (Upstream &amp; Downstream) sector of India. Periodic safety audits of industry, regular reviews for improvement, knowledge and experience sharing are done to achieve highest safety standards in a cost effective manner. The offshore safety regulations are being framed presently by OISD for fast expanding offshore exploration and development activities in India with knowledge and assistance from International Regulatory bodies.</p>
          <p>&nbsp;</p>
          <h3>Djibril Amadou Kanoute, Senegal <br />
            Operations Manager, PETROSEN, Senegal National Oil Company</h3>
          <p><img src="/conferences/2007conference/speakers/DjibrilKanoute.jpg" alt="Djibril Amadou Kanoute, Senegal" width="134" height="156" hspace="10" align="left" />Mr. Djibril Kanoute is from Senegal. Senegal is located in West Africa and is not yet an oil producing country. </p>
          <p>He graduated as a Mining Engineer from the Mining School of Rabat in Morocco. He started his career in the early 80&rsquo;s at the Direction of Mines and Geology of the Ministry of Industrial Development of his country.</p>
          <p>He joined Tullow Oil in 1986. Tullow Oil is an Irish company that first started its activities in Senegal. He worked as a Field Engineer, and specialised in Drilling and Production operations. In 1990, he left Tullow Oil for PETROSEN where he was appointed in 1992 as Manager of the Production Department and later as Operation Manager when the company acquired a land drilling rig in 1996.</p>
          <p>Between 1986 and 1996 he took many short courses in Drilling and Production Operations in Canada within the OGCI (Oil &amp; Gas Consultants International Inc), PITS (Petroleum Industry Training Service) and in France at the IFP (Institut Fran&ccedil;ais du Petrole). He also attended many seminars in Loss Control Management and Occupational Health, Safety and Environmental Management.</p>
          <p>From year 2000 until today, he moved to the management of the company as an Operation Advisor to the General Manager. He initiated the redaction of the terms of reference for the regulation of exploration and production operations in order to complete petroleum legislation of his country.</p>
          <p>&nbsp;</p>
          <h3>Ian Ramdahin, Trinidad and Tobago <br />
            Chief Mechanical Engineer, Ministry of Energy and Energy Industries</h3>
          <p><img src="/conferences/2007conference/speakers/IanRamdahin.jpg" alt="Ian Ramdahin, Trinidad and Tobago" width="134" height="156" hspace="10" align="left" />Mr Ian Ramdahin is currently the head of the HSE/Measurement Division, Ministry of Energy and Energy Industries (MEEI), Republic of Trinidad and Tobago, as well as a board member of the Trinidad and Tobago Occupational Health and Safety Authority which was recently instituted in October 2006. He is an Engineering graduate from the University of the West Indies who has over ten years of regulatory experience in the HSE field. A major achievement in his career so far has been his role in the development of the Trinidad and Tobago Verification Scheme Regime as a HSE tool for establishing technical assurance.</p>
          <p>&nbsp;</p>
          <p>&nbsp;</p>
          <h3>Raphael Neves Moura, Brazil <br />
            Nacional Petroleum Agency (ANP)</h3>
          <p><img src="/conferences/2007conference/speakers/RMoura.jpg" alt="Raphael Neves Moura, Brazil" width="134" height="171" hspace="10" align="left" />Mr. Moura earned a Bachelors degree in Production Engineering from Technical College and postgraduated in Offshore Systems Engineering at the Federal University of Rio de Janeiro. </p>
          <p>He worked from 1996 to 2005 for Siem Consub SA (Siem Offshore Inc. Brazilian Subsidiary) as Project Engineer at several projects comprising naval and underwater technology. In addition, Mr. Moura was responsible for the diffusion of Integrated Management System (Safety, Quality and Environment &ndash; ISO 9000 / ISO 14001 / OHSAS 18001) and was appointed as President of Internal Commission of Accidents Prevention for 2004. </p>
          <p>Since November 2005 he has been working for the National Petroleum Agency (ANP*), dealing with inspections, auditing and investigating accidents at onshore and offshore Production Facilities. In May 2007, ANP Board of Directors appointed Mr. Moura as Head of the Safety Division, and he played a central role on the establishment of the new offshore safety regulatory model. </p>
          <p></p></td>
        </tr>
    </table></td>
  </tr>
</table>
<!--#include virtual="/shared/footer.aspx" -->
</body>
</html>
